# Kafka 接続設定
# 環境変数 KAFKA_BOOTSTRAP_SERVERS が設定されている場合はそちらを優先する
bootstrap.servers=20.27.136.160:9092

# Producer 設定
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
acks=all

# Consumer 設定
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
auto.offset.reset=earliest
enable.auto.commit=true
